<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Qualification extends Model
{
    use HasFactory;

    protected $fillable = [
        'employee_id',
        'degree_name',
        'degree_qualification_name',
        'institute_name',
        'date_from',
        'date_to',
        'total_score',
        'obtain_score',
        'division',
        'passing_year',
        'field_subject',
        'major_specialization',
        'national_foreign',
        'country',
        'province_state',
        'district_city_location',
        'degree_status',
        'verified_from_hec',
        'attachment',
    ];

    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }


    public static function country()
    {
        return [
            'Afghanistan',
            'Albania',
            'Algeria',
            'Andorra',
            'Angola',
            'Antigua & Deps',
            'Argentina',
            'Armenia',
            'Australia',
            'Austria',
            'Azerbaijan',
            'Bahamas',
            'Bahrain',
            'Bangladesh',
            'Barbados',
            'Belarus',
            'Belgium',
            'Belize',
            'Benin',
            'Bhutan',
            'Bolivia',
            'Bosnia Herzegovina',
            'Botswana',
            'Brazil',
            'Brunei',
            'Bulgaria',
            'Burkina',
            'Burundi',
            'Cambodia',
            'Cameroon',
            'Canada',
            'Cape Verde',
            'Central African Rep',
            'Chad',
            'Chile',
            'China',
            'Colombia',
            'Comoros',
            'Congo',
            'Congo {Democratic Rep}',
            'Costa Rica',
            'Croatia',
            'Cuba',
            'Cyprus',
            'Czech Republic',
            'Denmark',
            'Djibouti',
            'Dominica',
            'Dominican Republic',
            'East Timor',
            'Ecuador',
            'Egypt',
            'El Salvador',
            'Equatorial Guinea',
            'Eritrea',
            'Estonia',
            'Ethiopia',
            'Fiji',
            'Finland',
            'France',
            'Gabon',
            'Gambia',
            'Georgia',
            'Germany',
            'Ghana',
            'Greece',
            'Grenada',
            'Guatemala',
            'Guinea',
            'Guinea-Bissau',
            'Guyana',
            'Haiti',
            'Honduras',
            'Hungary',
            'Iceland',
            'India',
            'Indonesia',
            'Iran',
            'Iraq',
            'Ireland {Republic}',
            'Israel',
            'Italy',
            'Ivory Coast',
            'Jamaica',
            'Japan',
            'Jordan',
            'Kazakhstan',
            'Kenya',
            'Kiribati',
            'Korea North',
            'Korea South',
            'Kosovo',
            'Kuwait',
            'Kyrgyzstan',
            'Laos',
            'Latvia',
            'Lebanon',
            'Lesotho',
            'Liberia',
            'Libya',
            'Liechtenstein',
            'Lithuania',
            'Luxembourg',
            'Macedonia',
            'Madagascar',
            'Malawi',
            'Malaysia',
            'Maldives',
            'Mali',
            'Malta',
            'Marshall Islands',
            'Mauritania',
            'Mauritius',
            'Mexico',
            'Micronesia',
            'Moldova',
            'Monaco',
            'Mongolia',
            'Montenegro',
            'Morocco',
            'Mozambique',
            'Myanmar, {Burma}',
            'Namibia',
            'Nauru',
            'Nepal',
            'Netherlands',
            'New Zealand',
            'Nicaragua',
            'Niger',
            'Nigeria',
            'Norway',
            'Oman',
            'Pakistan',
            'Palau',
            'Panama',
            'Papua New Guinea',
            'Paraguay',
            'Peru',
            'Philippines',
            'Poland',
            'Portugal',
            'Qatar',
            'Romania',
            'Russian Federation',
            'Rwanda',
            'St Kitts & Nevis',
            'St Lucia',
            'Saint Vincent & the Grenadines',
            'Samoa',
            'San Marino',
            'Sao Tome & Principe',
            'Saudi Arabia',
            'Senegal',
            'Serbia',
            'Seychelles',
            'Sierra Leone',
            'Singapore',
            'Slovakia',
            'Slovenia',
            'Solomon Islands',
            'Somalia',
            'South Africa',
            'South Sudan',
            'Spain',
            'Sri Lanka',
            'Sudan',
            'Suriname',
            'Swaziland',
            'Sweden',
            'Switzerland',
            'Syria',
            'Taiwan',
            'Tajikistan',
            'Tanzania',
            'Thailand',
            'Togo',
            'Tonga',
            'Trinidad & Tobago',
            'Tunisia',
            'Turkey',
            'Turkmenistan',
            'Tuvalu',
            'Uganda',
            'Ukraine',
            'United Arab Emirates',
            'United Kingdom',
            'United States',
            'Uruguay',
            'Uzbekistan',
            'Vanuatu',
            'Vatican City',
            'Venezuela',
            'Vietnam',
            'Yemen',
            'Zambia',
            'Zimbabwe',
        ];
    }


    public static function training_type(): array
    {
        $training_type = [
            'Certificate',
            'Diploma',
            'Distant Learning',
            'Online',
            'CCNA',
            'CCNP',
        ];
        return $training_type;
    }

    public static function degree_list()
    {
        $degree = [
            "GENERAL AGRICULTURE" => "Agriculture & Natural Resources",
            "AGRICULTURE PRODUCTION AND MANAGEMENT" => "Agriculture & Natural Resources",
            "AGRICULTURAL ECONOMICS" => "Agriculture & Natural Resources",
            "ANIMAL SCIENCES" => "Agriculture & Natural Resources",
            "FOOD SCIENCE" => "Agriculture & Natural Resources",
            "PLANT SCIENCE AND AGRONOMY" => "Agriculture & Natural Resources",
            "SOIL SCIENCE" => "Agriculture & Natural Resources",
            "MISCELLANEOUS AGRICULTURE" => "Agriculture & Natural Resources",
            "FORESTRY" => "Agriculture & Natural Resources",
            "NATURAL RESOURCES MANAGEMENT" => "Agriculture & Natural Resources",
            "FINE ARTS" => "Arts",
            "DRAMA AND THEATER ARTS" => "Arts",
            "MUSIC" => "Arts",
            "VISUAL AND PERFORMING ARTS" => "Arts",
            "COMMERCIAL ART AND GRAPHIC DESIGN" => "Arts",
            "FILM VIDEO AND PHOTOGRAPHIC ARTS" => "Arts",
            "STUDIO ARTS" => "Arts",
            "MISCELLANEOUS FINE ARTS" => "Arts",
            "ENVIRONMENTAL SCIENCE" => "Biology & Life Science",
            "BIOLOGY" => "Biology & Life Science",
            "BIOCHEMICAL SCIENCES" => "Biology & Life Science",
            "BOTANY" => "Biology & Life Science",
            "MOLECULAR BIOLOGY" => "Biology & Life Science",
            "ECOLOGY" => "Biology & Life Science",
            "GENETICS" => "Biology & Life Science",
            "MICROBIOLOGY" => "Biology & Life Science",
            "PHARMACOLOGY" => "Biology & Life Science",
            "PHYSIOLOGY" => "Biology & Life Science",
            "ZOOLOGY" => "Biology & Life Science",
            "NEUROSCIENCE" => "Biology & Life Science",
            "MISCELLANEOUS BIOLOGY" => "Biology & Life Science",
            "COGNITIVE SCIENCE AND BIOPSYCHOLOGY" => "Biology & Life Science",
            "GENERAL BUSINESS" => "Business",
            "ACCOUNTING" => "Business",
            "ACTUARIAL SCIENCE" => "Business",
            "BUSINESS MANAGEMENT AND ADMINISTRATION" => "Business",
            "OPERATIONS LOGISTICS AND E-COMMERCE" => "Business",
            "BUSINESS ECONOMICS" => "Business",
            "MARKETING AND MARKETING RESEARCH" => "Business",
            "FINANCE" => "Business",
            "HUMAN RESOURCES AND PERSONNEL MANAGEMENT" => "Business",
            "INTERNATIONAL BUSINESS" => "Business",
            "HOSPITALITY MANAGEMENT" => "Business",
            "MANAGEMENT INFORMATION SYSTEMS AND STATISTICS" => "Business",
            "MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION" => "Business",
            "COMMUNICATIONS" => "Communications & Journalism",
            "JOURNALISM" => "Communications & Journalism",
            "MASS MEDIA" => "Communications & Journalism",
            "ADVERTISING AND PUBLIC RELATIONS" => "Communications & Journalism",
            "COMMUNICATION TECHNOLOGIES" => "Computers & Mathematics",
            "COMPUTER AND INFORMATION SYSTEMS" => "Computers & Mathematics",
            "COMPUTER PROGRAMMING AND DATA PROCESSING" => "Computers & Mathematics",
            "COMPUTER SCIENCE" => "Computers & Mathematics",
            "INFORMATION SCIENCES" => "Computers & Mathematics",
            "COMPUTER ADMINISTRATION MANAGEMENT AND SECURITY" => "Computers & Mathematics",
            "COMPUTER NETWORKING AND TELECOMMUNICATIONS" => "Computers & Mathematics",
            "MATHEMATICS" => "Computers & Mathematics",
            "APPLIED MATHEMATICS" => "Computers & Mathematics",
            "STATISTICS AND DECISION SCIENCE" => "Computers & Mathematics",
            "MATHEMATICS AND COMPUTER SCIENCE" => "Computers & Mathematics",
            "GENERAL EDUCATION" => "Education",
            "EDUCATIONAL ADMINISTRATION AND SUPERVISION" => "Education",
            "SCHOOL STUDENT COUNSELING" => "Education",
            "ELEMENTARY EDUCATION" => "Education",
            "MATHEMATICS TEACHER EDUCATION" => "Education",
            "PHYSICAL AND HEALTH EDUCATION TEACHING" => "Education",
            "EARLY CHILDHOOD EDUCATION" => "Education",
            "SCIENCE AND COMPUTER TEACHER EDUCATION" => "Education",
            "SECONDARY TEACHER EDUCATION" => "Education",
            "SPECIAL NEEDS EDUCATION" => "Education",
            "SOCIAL SCIENCE OR HISTORY TEACHER EDUCATION" => "Education",
            "TEACHER EDUCATION: MULTIPLE LEVELS" => "Education",
            "LANGUAGE AND DRAMA EDUCATION" => "Education",
            "ART AND MUSIC EDUCATION" => "Education",
            "MISCELLANEOUS EDUCATION" => "Education",
            "LIBRARY SCIENCE" => "Education",
            "ARCHITECTURE" => "Engineering",
            "GENERAL ENGINEERING" => "Engineering",
            "AEROSPACE ENGINEERING" => "Engineering",
            "BIOLOGICAL ENGINEERING" => "Engineering",
            "ARCHITECTURAL ENGINEERING" => "Engineering",
            "BIOMEDICAL ENGINEERING" => "Engineering",
            "CHEMICAL ENGINEERING" => "Engineering",
            "CIVIL ENGINEERING" => "Engineering",
            "COMPUTER ENGINEERING" => "Engineering",
            "ELECTRICAL ENGINEERING" => "Engineering",
            "ENGINEERING MECHANICS PHYSICS AND SCIENCE" => "Engineering",
            "ENVIRONMENTAL ENGINEERING" => "Engineering",
            "GEOLOGICAL AND GEOPHYSICAL ENGINEERING" => "Engineering",
            "INDUSTRIAL AND MANUFACTURING ENGINEERING" => "Engineering",
            "MATERIALS ENGINEERING AND MATERIALS SCIENCE" => "Engineering",
            "MECHANICAL ENGINEERING" => "Engineering",
            "METALLURGICAL ENGINEERING" => "Engineering",
            "MINING AND MINERAL ENGINEERING" => "Engineering",
            "NAVAL ARCHITECTURE AND MARINE ENGINEERING" => "Engineering",
            "NUCLEAR ENGINEERING" => "Engineering",
            "PETROLEUM ENGINEERING" => "Engineering",
            "MISCELLANEOUS ENGINEERING" => "Engineering",
            "ENGINEERING TECHNOLOGIES" => "Engineering",
            "ENGINEERING AND INDUSTRIAL MANAGEMENT" => "Engineering",
            "ELECTRICAL ENGINEERING TECHNOLOGY" => "Engineering",
            "INDUSTRIAL PRODUCTION TECHNOLOGIES" => "Engineering",
            "MECHANICAL ENGINEERING RELATED TECHNOLOGIES" => "Engineering",
            "MISCELLANEOUS ENGINEERING TECHNOLOGIES" => "Engineering",
            "MATERIALS SCIENCE" => "Engineering",
            "NUTRITION SCIENCES" => "Health",
            "GENERAL MEDICAL AND HEALTH SERVICES" => "Health",
            "COMMUNICATION DISORDERS SCIENCES AND SERVICES" => "Health",
            "HEALTH AND MEDICAL ADMINISTRATIVE SERVICES" => "Health",
            "MEDICAL ASSISTING SERVICES" => "Health",
            "MEDICAL TECHNOLOGIES TECHNICIANS" => "Health",
            "HEALTH AND MEDICAL PREPARATORY PROGRAMS" => "Health",
            "NURSING" => "Health",
            "PHARMACY PHARMACEUTICAL SCIENCES AND ADMINISTRATION" => "Health",
            "TREATMENT THERAPY PROFESSIONS" => "Health",
            "COMMUNITY AND PUBLIC HEALTH" => "Health",
            "MISCELLANEOUS HEALTH MEDICAL PROFESSIONS" => "Health",
            "AREA ETHNIC AND CIVILIZATION STUDIES" => "Humanities & Liberal Arts",
            "LINGUISTICS AND COMPARATIVE LANGUAGE AND LITERATURE" => "Humanities & Liberal Arts",
            "FRENCH GERMAN LATIN AND OTHER COMMON FOREIGN LANGUAGE STUDIES" => "Humanities & Liberal Arts",
            "OTHER FOREIGN LANGUAGES" => "Humanities & Liberal Arts",
            "ENGLISH LANGUAGE AND LITERATURE" => "Humanities & Liberal Arts",
            "COMPOSITION AND RHETORIC" => "Humanities & Liberal Arts",
            "LIBERAL ARTS" => "Humanities & Liberal Arts",
            "HUMANITIES" => "Humanities & Liberal Arts",
            "INTERCULTURAL AND INTERNATIONAL STUDIES" => "Humanities & Liberal Arts",
            "PHILOSOPHY AND RELIGIOUS STUDIES" => "Humanities & Liberal Arts",
            "THEOLOGY AND RELIGIOUS VOCATIONS" => "Humanities & Liberal Arts",
            "ANTHROPOLOGY AND ARCHEOLOGY" => "Humanities & Liberal Arts",
            "ART HISTORY AND CRITICISM" => "Humanities & Liberal Arts",
            "HISTORY" => "Humanities & Liberal Arts",
            "UNITED STATES HISTORY" => "Humanities & Liberal Arts",
            "COSMETOLOGY SERVICES AND CULINARY ARTS" => "Industrial Arts & Consumer Services",
            "FAMILY AND CONSUMER SCIENCES" => "Industrial Arts & Consumer Services",
            "MILITARY TECHNOLOGIES" => "Industrial Arts & Consumer Services",
            "PHYSICAL FITNESS PARKS RECREATION AND LEISURE" => "Industrial Arts & Consumer Services",
            "CONSTRUCTION SERVICES" => "Industrial Arts & Consumer Services",
            "ELECTRICAL, MECHANICAL, AND PRECISION TECHNOLOGIES AND PRODUCTION" => "Industrial Arts & Consumer Services",
            "TRANSPORTATION SCIENCES AND TECHNOLOGIES" => "Industrial Arts & Consumer Services",
            "MULTI/INTERDISCIPLINARY STUDIES" => "Interdisciplinary",
            "COURT REPORTING" => "Law & Public Policy",
            "PRE-LAW AND LEGAL STUDIES" => "Law & Public Policy",
            "CRIMINAL JUSTICE AND FIRE PROTECTION" => "Law & Public Policy",
            "PUBLIC ADMINISTRATION" => "Law & Public Policy",
            "PUBLIC POLICY" => "Law & Public Policy",
            "N/A (less than bachelor's degree)" => "NA",
            "PHYSICAL SCIENCES" => "Physical Sciences",
            "ASTRONOMY AND ASTROPHYSICS" => "Physical Sciences",
            "ATMOSPHERIC SCIENCES AND METEOROLOGY" => "Physical Sciences",
            "CHEMISTRY" => "Physical Sciences",
            "GEOLOGY AND EARTH SCIENCE" => "Physical Sciences",
            "GEOSCIENCES" => "Physical Sciences",
            "OCEANOGRAPHY" => "Physical Sciences",
            "PHYSICS" => "Physical Sciences",
            "MULTI-DISCIPLINARY OR GENERAL SCIENCE" => "Physical Sciences",
            "NUCLEAR, INDUSTRIAL RADIOLOGY, AND BIOLOGICAL TECHNOLOGIES" => "Physical Sciences",
            "PSYCHOLOGY" => "Psychology & Social Work",
            "EDUCATIONAL PSYCHOLOGY" => "Psychology & Social Work",
            "CLINICAL PSYCHOLOGY" => "Psychology & Social Work",
            "COUNSELING PSYCHOLOGY" => "Psychology & Social Work",
            "INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY" => "Psychology & Social Work",
            "SOCIAL PSYCHOLOGY" => "Psychology & Social Work",
            "MISCELLANEOUS PSYCHOLOGY" => "Psychology & Social Work",
            "HUMAN SERVICES AND COMMUNITY ORGANIZATION" => "Psychology & Social Work",
            "SOCIAL WORK" => "Psychology & Social Work",
            "INTERDISCIPLINARY SOCIAL SCIENCES" => "Social Science",
            "GENERAL SOCIAL SCIENCES" => "Social Science",
            "ECONOMICS" => "Social Science",
            "CRIMINOLOGY" => "Social Science",
            "GEOGRAPHY" => "Social Science",
            "INTERNATIONAL RELATIONS" => "Social Science",
            "POLITICAL SCIENCE AND GOVERNMENT" => "Social Science",
            "SOCIOLOGY" => "Social Science",
            "MISCELLANEOUS SOCIAL SCIENCES" => "Social Science",
            "Matric Science" => "Matric Science",
            "Matric Arts" => "Matric Arts",
            "O Level" => "O Level",
            "FA" => "FA",
            "FSc Pre-M" => "FSc Pre-M",
            "FSc Pre-Engg" => "FSc Pre-Engg",
            "A-Level" => "A-Level",
            "BA Arts" => "BA Arts",
            "MA" => "MA",
            "MBA" => "MBA",
            "BA" => "BA",
            "BCS" => "BCS",
            "BSC" => "BSC",
            "MBBS" => "MBBS",
            "BE" => "BE",
            "M.Phil" => "M.Phil",
            "MSCS" => "MSCS",
            "PHD" => "PHD",
        ];

        ksort($degree);
        return $degree;
    }


    public static function verified_hec(): array
    {
        return [
            'Yes',
            'No',
            'In Process',
        ];
    }


    public static function degree_status(): array
    {
        return [
            'Completed',
            'In Process',
            'Freeze',
        ];
    }

    public static function province_state(): array
    {
        $province_state = [
            'Azad Jammu and Kashmir',
            'Gilgit-Baltistan',
            'Islamabad Capital Territory',
            'Pubjab',
            'Sindh',
            'Khyber Pakhtunkhwa',
            'Baluchistan',
            'Other/Not Listed',
        ];

//        sort($province_state);
        return $province_state;
    }

    public static function national_foreign(): array
    {
        $national_foreign = [
            'National',
            'Foreign Qualified',
        ];

        sort($national_foreign);
        return $national_foreign;
    }

    public static function degree_name()
    {
        $degree_name = [
            'Secondary School Certificate / Matriculation / O - level',
            'Higher Secondary School Certificate / Intermediate/ A - level',
            'Bachelor (14 Years) Degree',
            'Bachelor (15 Years) Degree',
            'Bachelor (16 Years) Degree',
            'Master (16 Years) Degree',
            'Master (17 years) Degree',
            'Master/ MS (18 Years) Degree',
            'M-Phil (18 Years) Degree',
            'Doctorate Degree',
            'MS leading to PhD',
            'Post Doctorate',
            'PGD',
        ];

//        sort($degree_name);
        return $degree_name;
    }




}
